/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package vista;

import controlador.ESaldoNoValido;
import static controlador.GestionFicheros.formateaFecha;
import controlador.Lista;
import controlador.Nodo;
import java.awt.event.ActionEvent;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Cuenta;
import modelo.CuentaAhorro;
import modelo.CuentaCorriente;

/**
 *
 * @author Pernas
 */
public class NuevaCuenta extends javax.swing.JPanel {

    private Lista listaNodo;
    
    /** Creates new form NuevaCuenta */
    public NuevaCuenta(Lista listanodo) {
        initComponents();
        listaNodo = listanodo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitular = new javax.swing.JLabel();
        jLabelSaldoActual = new javax.swing.JLabel();
        jLabelSaldoMinimo = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelTipo1 = new javax.swing.JLabel();
        jLabelTipo2 = new javax.swing.JLabel();
        jTextFieldTitular = new javax.swing.JTextField();
        jTextFieldSaldoActual = new javax.swing.JTextField();
        jTextFieldSaldoMinimo = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldTipo1 = new javax.swing.JTextField();
        jTextFieldTipo2 = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        jLabelTitular.setText("Titular");

        jLabelSaldoActual.setText("Saldo actual");

        jLabelSaldoMinimo.setText("Saldo Minimo");

        jLabelFecha.setText("Fecha");

        jLabelTipo1.setText("Tipo 1");

        jLabelTipo2.setText("Tipo 2");

        jTextFieldTipo2.setText("jTextField7");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTipo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSaldoMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jTextFieldSaldoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSaldoActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipo2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButtonGuardar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVolver)
                            .addComponent(jTextFieldTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitular)
                    .addComponent(jTextFieldTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSaldoActual)
                    .addComponent(jTextFieldSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSaldoMinimo)
                    .addComponent(jTextFieldSaldoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo1)
                    .addComponent(jTextFieldTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo2)
                    .addComponent(jTextFieldTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonVolver))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        crearCuenta();
        for(Nodo n: listaNodo.getArrayNodos()) {
            System.out.println(n);
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelSaldoActual;
    private javax.swing.JLabel jLabelSaldoMinimo;
    private javax.swing.JLabel jLabelTipo1;
    private javax.swing.JLabel jLabelTipo2;
    private javax.swing.JLabel jLabelTitular;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldSaldoActual;
    private javax.swing.JTextField jTextFieldSaldoMinimo;
    private javax.swing.JTextField jTextFieldTipo1;
    private javax.swing.JTextField jTextFieldTipo2;
    private javax.swing.JTextField jTextFieldTitular;
    // End of variables declaration//GEN-END:variables

    public void modificaLabels(ActionEvent evt) {
        // System.out.println(evt.getSource().toString());
        if(evt.getSource().toString().contains("text=Ahorro")) {
            jLabelTipo1.setText("Interes Mensual");
            jLabelTipo2.setText("Bloqueada");
        } else {
            jLabelTipo1.setText("Comision mantenimiento");
            jLabelTipo2.setText("Tipo comision");
        }
    }

    public void vaciarTextFields() {
        
        jTextFieldFecha.setText(formateaFecha(Calendar.getInstance()));
        jTextFieldSaldoActual.setText("");
        jTextFieldSaldoMinimo.setText("");
        jTextFieldTipo1.setText("");
        jTextFieldTipo2.setText("");
        jTextFieldTitular.setText("");
        jTextFieldFecha.setEditable(false);
    }

    private void crearCuenta() {
        
        Cuenta c = null;
        String cadenaBloqueada = jTextFieldTipo2.getText(); // Cadena que se ha escrito en el text field
        boolean bloqueada; // Variable que va a guardar si la cuenta esta bloqueada (true) o no (false)
        if (cadenaBloqueada.equalsIgnoreCase("si") || cadenaBloqueada.equalsIgnoreCase("no"))
            bloqueada = bloqueada(cadenaBloqueada);
        
        if("Interes Mensual".equals(jLabelTipo1.getText())) {
            Calendar cal = Calendar.getInstance();
            try {
                c = new CuentaAhorro(
                        Double.parseDouble(jTextFieldTipo1.getText()),
                        bloqueada(jTextFieldTipo2.getText()),
                        jTextFieldTitular.getText(),
                        Double.parseDouble(jTextFieldSaldoActual.getText()),
                        Double.parseDouble(jTextFieldSaldoMinimo.getText()),
                        cal);
            } catch (ESaldoNoValido ex) {
                Logger.getLogger(NuevaCuenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                c = new CuentaCorriente(
                        Float.parseFloat(jTextFieldTipo1.getText()),
                        jTextFieldTipo2.getText(),
                        jTextFieldTitular.getText(),
                        Double.parseDouble(jTextFieldSaldoActual.getText()),
                        Double.parseDouble(jTextFieldSaldoMinimo.getText()),
                        Calendar.getInstance());
            } catch (ESaldoNoValido ex) {
                Logger.getLogger(NuevaCuenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        listaNodo.insertar(c.getNumero(), c);
    }

    private boolean bloqueada(String text) {
        return text.equalsIgnoreCase("si");
    }
    
    public Lista getListaNodos (){
        return this.listaNodo;
    } 
}
